baseURL = 'http://chenycherry.top'
languageCode = 'zh-cn'
title = "Cheny's Blog"
theme = 'void'

#Main Menu

[[menus.main]]
name ='Home'
PageRef ='/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'